import 'zone.js/dist/zone-node'; // needs for change detection on server
import * as functions from 'firebase-functions';
import * as express from 'express';
import { renderModuleFactory } from '@angular/platform-server'; // allows us to generate the HTML and CSS
import * as fs from 'fs';

// reads index.html file from the filesystem, comes back in utf8 format
const document = fs.readFileSync(__dirname + '/dist-server/index.html', 'utf8');

// requires Universal Bundle that was generated by the Angular CLI, and we can use this to generate HTML and CSS
const AppServerModuleNgFactory = require(__dirname + '/dist-server/main.bundle').AppServerModuleNgFactory;

// Server
const app = express();
// Http Handler (** = intercept every single route)
app.get('**', (req, res) => {
    const url = req.path;
    renderModuleFactory(AppServerModuleNgFactory, { document, url })
        .then(html => {
            // Cach Control Heading. This content will be cached for 5 minutes and it will be cached for 10 minutes on CDN level
            res.set('Cach-Control', 'public, max-age=600, s-maxage=1200');
            res.send(html); // send back html
        });
});

export let ssrapp = functions.https.onRequest(app);